version: "3.8"

services:
  node:
    build: .
    container_name: node-terminal
    volumes:
      - ./:/workspace
    stdin_open: true
    tty: true
    ports:
      - "9000:9000"
      - "8502:8502"
      - "8501:8501"
      - "8500:8500"